[project]
name = "mypackage"
version = "0.1.0"
description = "A Python package template using Nix and uv"
authors = [
    {name = "Your Name", email = "your.email@example.com"},
]
dependencies = [
    "beartype>=0.19.0",
    "expression>=5.5.0",
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "AGPL-3.0-or-later"}

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.optional-dependencies]

[dependency-groups]
lint = [
    "ruff>=0.9.4",
]
test = [
    "hypothesis>=6.125.1",
    "pytest>=8.3.4",
    "pytest-cov>=6.0.0",
    "xdoctest>=1.2.0",
]
types = [
    "pyright>=1.1.393",
]
dev = [
    {include-group = "lint"},
    {include-group = "test"},
    {include-group = "types"},
]

[tool.uv]
default-groups = ["lint", "test", "types"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64","osx-arm64"]
preview = ["pixi-build"]

[tool.pixi.dependencies]
python = ">=3.11"
beartype = ">=0.19.0"
expression = ">=5.5.0"

[tool.pixi.pypi-dependencies]
mypackage = { path = ".", editable = true }

[tool.pixi.environments]
default = { solve-group = "default" }
lint = { features = ["lint"], solve-group = "default" }
test = { features = ["test"], solve-group = "default" }
types = { features = ["types"], solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }

[tool.pixi.feature.test.tasks]
test = "pytest"

[tool.pixi.feature.lint.tasks]
lint = "ruff check src/"
lint-fix = "ruff check --fix src/"

[tool.pixi.feature.types.tasks]
types = "pyright src/"

[tool.pixi.package]
name = "mypackage"
version = "0.1.0"

[tool.pixi.package.run-dependencies]
beartype = ">=0.19.0"
expression = ">=5.5.0"

[tool.pixi.package.build]
backend = { name = "pixi-build-python", version = "0.1.*" }
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]

[tool.hatch.build.targets.wheel]
packages = ["src/mypackage"]

[tool.pytest.ini_options]
addopts = """
-rA
--xdoctest
--disable-warnings
--cov=src/mypackage/
--cov-report=term-missing
--durations=0
"""
log_level = "INFO"
testpaths = [
    "src/mypackage/tests",
]

[tool.ruff]
line-length = 88
target-version = "py311"
src = ["src"]

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
] 
