[project]
name = "mypackage"
version = "0.1.0"
description = "A Python package template using Nix and uv"
authors = [
    {name = "Your Name", email = "your.email@example.com"},
]
dependencies = [
    "beartype>=0.19.0",
    "expression>=5.5.0",
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "AGPL-3.0-or-later"}

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.optional-dependencies]

[dependency-groups]
dev = [
    "pyright>=1.1.393",
]
test = [
    "hypothesis>=6.125.1",
    "pytest>=8.3.4",
    "pytest-cov>=6.0.0",
    "xdoctest>=1.2.0",
]
lint = [
    "ruff>=0.9.4",
]

[tool.uv]
default-groups = ["dev", "lint", "test"]

[tool.hatch.build.targets.wheel]
packages = ["src/mypackage"]

[tool.pytest.ini_options]
addopts = """
-rA
--xdoctest
--disable-warnings
--cov=src/mypackage/
--cov-report=term-missing
--durations=0
"""
testpaths = [
    "src/mypackage/tests",
]

[tool.ruff]
line-length = 88
target-version = "py311"
src = ["src"]

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
] 
