contact_links:
  - name: questions
    url: https://github.com/sciexp/python-nix-template/discussions
    about: please post and host discussion in https://github.com/sciexp/python-nix-template/discussions
