name: PR Check Fast-forward
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  check-fast-forward:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: check fast-forward merge is possible
        uses: sequoia-pgp/fast-forward@6f66e12ccb351059900f82fcd87e8d9e9c095087 # ratchet:sequoia-pgp/fast-forward@main
        with:
          merge: false
          comment: on-error
